name: belucar_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  flutter_localizations:
    sdk: flutter
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^17.0.0
  change_app_package_name: ^1.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/icons/icons8-zalo-100.png
    - lib/assets/icons/united-states.png
    - lib/assets/icons/vietnam.png
    - lib/assets/icons/BeluCar_logo.jpg
    - lib/assets/icons/ActivityLogo.png
    - lib/assets/tet_splash.png
    - lib/assets/icons/tet_launcher_icon.png
    - lib/assets/carousel_01.jpg
    - lib/assets/carousel_02.png
    - lib/assets/carousel_03.jpg
    - lib/assets/icons/new_launcher_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/new_launcher_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/icons/new_launcher_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
